#====================================================================================================
# Argument reference (https://registry.terraform.io/providers/SumoLogic/sumologic/latest/docs/resources/cse_match_rule) 
#====================================================================================================
# index_key                 (Required) Primary key used internally, not sent to Sumo. Must be unique
# enabled                   (Required) Whether the rule should generate Signals
# name                      (Required) The name of the Rule
# name_expression           (Required) The name of the generated Signals
# summary_expression        (Optional) The summary of the generated Signals
# description_expression    (Required) The description of the generated Signals
# expression                (Required) The expression for which records to match on
# entity_selectors          (Required) The entities to generate Signals on
#     entityType            (Required) The type of the entity to generate the Signal on.
#     expression            (Required) The expression or field name to generate the Signal on.
# severity_mapping          (Required) The configuration of how the severity of the Signals should be mapped from the Records
#     type                  (Required) Whether to set a constant severity ("constant"), set the severity based on the direct value of a record field ("fieldValue"), or map a record field value to a severity ("fieldValueMapping").
#     default               (Optional) The severity to use in the "constant" case or to fall back to if the field used by "fieldValue"/"fieldValueMapping" is not populated.
#     field                 (Optional) The field to use in the "fieldValue"/"fieldValueMapping" cases.
#     mapping               (Optional) The map of record values to severities to use in the "fieldValueMapping" case
#       type                (Required) Must be set to "eq" currently
#       from                (Required) The record value to map from
#       to                  (Required) The severity value to map to
# tags                      (Required) The tags of the generated Signals
# is_prototype              (Optional) Whether the generated Signals should be prototype Signals
#====================================================================================================

#====================================================================================================
# Example usage
#==================================================================================================== 
- index_key: mar-1
  enabled: true
  name: "Sudo Command Line Detection"
  name_expression: "Sudo usage detected in command line"
  summary_expression: "Sudo usage detected on {{device_hostname}}"
  description_expression: "Sudo usage could suggest privilege escalation if performed in an unexpected context"
  expression: "contains(command_line, 'sudo')"
  entity_selectors:
    - entity_type: "_hostname"
      expression: "device_hostname"
  severity_mapping:
    - type: "constant"
      default: 1
  tags: 
    - _mitreAttackTechnique:T1548
    - _mitreAttackTactic:TA0004
  is_prototype: false
