#====================================================================================================
# Argument reference (https://registry.terraform.io/providers/SumoLogic/sumologic/latest/docs/resources/cse_custom_insight) 
#====================================================================================================
# index_key                      (Required) Primary key used internally, not sent to Sumo. Must be unique
# enabled                        (Required) Whether the Custom Insight should generate Insights
# name                           (Required) The name of the Custom Insight and the generated Insights
# description                    (Required) The description of the generated Insights
# ordered                        (Required) Whether the signals matching the rule IDs/signal names must be in the same chronological order as they are listed in the Custom Insight
# rule_ids                       (Optional) The Rule IDs to match to generate an Insight (exactly one of rule_ids or signal_names must be specified)
# severity                       (Required) The severity of the generated Insights (CRITICAL, HIGH, MEDIUM, or LOW)
# dynamic_severity               (Optional) The severity of the generated Insight that is based on the severity of the Signals that trigger the Insight.
#     minimum_signal_severity    (Required) minimum Signal severity as the threshold for an Insight severity level
#     insight_severity           (Required) The severity of the generated Insight (CRITICAL, HIGH, MEDIUM, or LOW)
# signal_names                   (Optional) The Signal names to match to generate an Insight (exactly one of rule_ids or signal_names must be specified)
# tags                           (Required) The tags of the generated Insights
#====================================================================================================

#====================================================================================================
# Example usage
#==================================================================================================== 
- index_key: cti-1
  enabled: True
  name: Example Custom Insight
  description: Example custom insight without dynamic severity
  ordered: True
  rule_ids: 
    - MATCH-U00001
  severity: CRITICAL
  tags:
    - custom_insight

- index_key: cti-2
  enabled: True
  name: Another Example Custom Insight
  description: Example custom insight with dynamic severity
  ordered: True
  rule_ids:
    - MATCH-S00001
    - THRESHOLD-U00001
  severity: HIGH
  dynamic_severity:
    - minimum_signal_severity: 8  
    - insight_severity: CRITICAL
  tags:
    - custom_insight
